#!/bin/sh
set -eu

lb config \
  --distribution bookworm \
  --archive-areas "main contrib non-free-firmware non-free" \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer live \
  --debian-installer-gui true \
  --iso-application "WeeDroid OS" \
  --iso-publisher "WeeDroid Project" \
  --iso-volume "WeeDroid Live" \
  --memtest none \
  --bootappend-live "boot=live components quiet splash username=weedroid hostname=weedroid"
